import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Tasks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Hello I am&nbsp;
            <code className={styles.code}>{props.name}</code>
          </p>
          {/* <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div> */}
        </div>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>
        <div className={styles.grid}>
          <Link
            href="/counter"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Counter <span>-&gt;</span>
            </h2>
            <p>
              Count the numbers using useState
            </p>
          </Link>
          <Link
            href="/list"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              List<span>-&gt;</span>
            </h2>
            <p>
              List of users from random API using axios, useEffect, useState.
            </p>
          </Link>
          <Link
            href="/propspass"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Props<span>-&gt;</span>
            </h2>
            <p>
              How to pass props from parent to child component
            </p>
          </Link>
          <Link
            href="/usememo"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              useMemo & useCallback<span>-&gt;</span>
            </h2>
            <p>
              Demonstrate the use of useMemo & useCallback
            </p>
          </Link>
          <Link
            href="/usememo"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              C R U D<span>-&gt;</span>
            </h2>
            <p>
              Create, Read, Update, Delete opreations unsing React js.
            </p>
          </Link>
          <Link
            href="/tictaetoe/app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Tic Tae Toe<span>-&gt;</span>
            </h2>
            <p>
            How to build a Tic-Tac-Toe Game using React Hooks ?
            </p>
          </Link>
          <Link
            href="/area"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
            Maximum Rectangular Area in a Histogram<span>-&gt;</span>
            </h2>
            {/* <p>
            How to build a Tic-Tac-Toe Game using React Hooks ?
            </p> */}
          </Link>
          <Link
            href="/merge"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
            Merge Without Extra Space<span>-&gt;</span>
            </h2>
            {/* <p>
            How to build a Tic-Tac-Toe Game using React Hooks ?
            </p> */}
          </Link>
          <Link
            href="/longestcommonsubsequence"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
            Longest Common Subsequence<span>-&gt;</span>
            </h2>
            {/* <p>
            How to build a Tic-Tac-Toe Game using React Hooks ?
            </p> */}
          </Link>
          <Link
            href="/hasZeroSumSubarray"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
            Subarray with 0 sum<span>-&gt;</span>
            </h2>
            {/* <p>
            How to build a Tic-Tac-Toe Game using React Hooks ?
            </p> */}
          </Link>
        </div>
      </main>
    </>
  )
}
